apiVersion: v1
kind: Pod
metadata:
  name: gcsfuse-pdv
  namespace: default
  annotations:
    gke-gcsfuse/volumes: "true"
spec:
  terminationGracePeriodSeconds: 60
  containers:
  - image: busybox
    name: busybox
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: gcsfuse-pdv
      mountPath: /data
      readOnly: true
  serviceAccountName: default
  volumes:
  - name: gcsfuse-pdv
    csi:
      driver: gcsfuse.csi.storage.gke.io
      volumeAttributes:
        bucketName: pdv-models