apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: gcsfuse-sc  # Use the StorageClass provided or created for GCS Fuse CSI
  resources:
    requests:
      storage: 1Gi  # This value is not really used since it’s GCS
