apiVersion: v1
kind: Service
metadata:
  name: promptdresser-service
spec:
  selector:
    app: promptdresser
  ports:
    - protocol: TCP
      port: 80        # Port exposed by the service
      targetPort: 8080  # Port your container is listening on
  type: LoadBalancer  # or ClusterIP/NodePort depending on your needs
